### ISSUE TITLE
Fix Storyboard warnings

### ISSUE THREAD

**Issue by jonbirge** [jonbirge/ecochef#26]

**Comment by UrvashiKoladiya** [comment]
@jonbirge I would like to fix this issue, Can you assigned it to me?

**Comment by urvi-k** [comment]
@jonbirge I would like to fix this, Can you please assigned it to me?

**Comment by jonbirge** [comment]
Happy to, @urvi-k thanks!

**Comment by urvi-k** [comment]
@jonbirge Storyboard warnings has been fixed, please review this PR: https://github.com/jonbirge/ecochef/pull/38
Thanks.

**Comment by jonbirge** [comment]
> @jonbirge Storyboard warnings has been fixed, please review this PR: #38 Thanks.

Everything compiled, @urvi-k . No errors, but I need to fix a couple buttons that moved. Once I do that I'll merge into the develop branch. Thanks again for the help! Are you ok if I credit you in the final app that goes on to the App Store. And if so, how would you like your name listed?

**Comment by urvi-k** [comment]
Thanks @jonbirge. let me know if you need any help.

It would be owner to me if you are willing to list my name on the App store. You can list my name as `Urvashi Koladiya`.

**Comment by jonbirge** [comment]
Done, @urvi-k . Version 1.1.1 will have you credited. I'll upload to the App Store next week.
